server:
  port: 9000

spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/?authSource=${MONGODB_DB}&replicaSet=${MONGODB_RS}
      database: ${MONGODB_DB}
logging:
  level:
    org.springframework.security: DEBUG
